/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import React, { useState } from 'react';

// Sections
import AdditionalDetails from '@/sections/AdditionalDetails';
import Services from '@/sections/Services';
import About from '@/sections/About';
import Consultation from '@/sections/Consultation';
import LactationServices from '@/sections/LactationServices';
import Appointments from '@/sections/Appointments';

import logo from '../images/logoCropped.png';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Loving Lactation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={`hamburger-menu ${menuOpen ? 'open' : ''}`} onClick={() => setMenuOpen(!menuOpen)}>
          <div className="bar-top"></div>
          <div className="bar-middle"></div>
          <div className="bar-bottom"></div>
        </div>
        <nav className={`navMenu ${menuOpen ? 'open' : ''}`}>
          <ul>
            <li>
              <a className="menu-item" href="#consultation" onClick={() => setMenuOpen(false)}>
                Consultation
              </a>
            </li>
            <li>
              <a className="menu-item" href="#about" onClick={() => setMenuOpen(false)}>
                About
              </a>
            </li>
            <li>
              <a className="menu-item" href="#services" onClick={() => setMenuOpen(false)}>
                Services
              </a>
            </li>
            <li>
              <a className="menu-item" href="#contact" onClick={() => setMenuOpen(false)}>
                Contact
              </a>
            </li>
          </ul>
        </nav>

        <section className="heroSection">
          <div className="logoWrapper">
            <img className="logo" src={logo.src} alt="logo" />
          </div>

          <h1>Loving Lactation</h1>
        </section>

        <Consultation />
        <LactationServices />
        <About />
        <Services />
        <Appointments />
        <AdditionalDetails />
      </main>
      <footer style={{ textAlign: 'center', padding: '1rem', background: '#F4ECE0' }}>
        (C) 2023 Loving Lactation LLC
      </footer>
    </>
  );
}
